#!/bin/sh

set -e

case "$1" in
    configure)
    easy_install pip
    pip uninstall -y docker || true
    pip uninstall -y docker-py || true
    pip install -r /usr/share/dockerator/requirements.txt
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac
